services:
  web-hyper-exkess-app:
    image: nginx:stable
    restart: always
    ports:
      - 1002:80
    volumes:
      - ./src:/var/www/html:ro
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - internal
    depends_on:
      - web-hyper-exkess-bot
    container_name: web-hyper-exkess-app

  web-hyper-exkess-bot:
    build: bot
    restart: always
    environment:
      APPNAME: Admin
      APPURL: http://proxy/
      APPURLREGEX: ^http(|s)://.*$$
      APPFLAG: HCS{hyper_eXkeSS_should_be_on_your_home_now_anyway_GG_for_solve_this_XSS_Challenge}
      APPLIMIT: 2
      APPLIMITTIME: 60
      USE_PROXY: 1
      DISPLAY: ${DISPLAY}
    networks:
      - internal
    container_name: web-hyper-exkess-bot

    # uncoment this if you need to run the bot in GUI mode
    # volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix

networks:
  internal:
